In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Salida.csv')

In [3]:
df.head(2)

,0,1950-01-30T01:34:11.520Z,33.6956667,-118.3898333,6.0,2.41,ml,5.0,277.0,0.4868,...,2016-01-28T17:58:15.530Z,"5km S of Rancho Palos Verdes, CA",earthquake,1.9,31.61,0.146,6.0.1,reviewed,ci.1,ci.2
0,1,1950-01-30T00:56:35.020Z,-53.472000,-71.073000,15.00,6.80,mw,NaN,NaN,NaN,...,2022-04-26T18:23:21.977Z,"36 km SSW of Punta Arenas, Chile",earthquake,NaN,25.00,0.200,NaN,reviewed,iscgem,iscgem
1,2,1950-01-29T05:21:16.030Z,34.000833,-117.568167,0.54,2.52,ml,8.0,121.0,0.1603,...,2016-01-28T18:12:06.570Z,"5km W of Mira Loma, CA",earthquake,0.88,2.16,0.253,8.0,reviewed,ci,ci

In [4]:
df.columns = ['fuera','time','latitude','longitude','depth','mag','magType','nst','gap','dmin','rms','net','id','updated','place','type','horizontalError','depthError','magError','magNst','status','locationSource','magSource']

In [5]:
pd.options.display.max_columns = 0
df.head(2)

   fuera                      time  ...  locationSource  magSource
0      1  1950-01-30T00:56:35.020Z  ...          iscgem     iscgem
1      2  1950-01-29T05:21:16.030Z  ...              ci         ci

[2 rows x 23 columns]

In [6]:
fila = {'fuera' : '0', 'time' : '1950-01-30T01:34:11.520Z', 'latitude' : '33.6956667', 'longitude' : '-118.3898333',
       'depth' : '6.0', 'mag' : '2.41', 'magType' : 'ml', 'nst' : '5.0', 'gap' : '277.0', 'dmin' : '0.4868',
       'rms' : '0.38', 'net' : 'ci', 'id' : 'ci3362482', 'updated' : '2016-01-28T17:58:15.530Z',
       'place' : '5km S of Rancho Palos Verdes, CA', 'type' : 'earthquake', 'horizontalError' : '1.9', 'depthError' : '31.61',
       'magError' : '0.146','magNst' : '6.0.1','status' : 'reviewed','locationSource' : 'ci.1', 'magSource' : 'ci.2'}

In [7]:
df = df.append(fila, ignore_index = True)

C:\Users\juseb\AppData\Local\Temp\ipykernel_4372\3261263708.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(fila, ignore_index = True)

In [8]:
#df['time'] = pd.to_datetime(df.time, errors = 'coerce')
df

         fuera                      time  ... locationSource magSource
0            1  1950-01-30T00:56:35.020Z  ...         iscgem    iscgem
1            2  1950-01-29T05:21:16.030Z  ...             ci        ci
2            3  1950-01-28T22:45:12.670Z  ...             ci        ci
3            4  1950-01-28T22:36:21.460Z  ...             ci        ci
4            5  1950-01-28T12:10:04.690Z  ...             ci        ci
...        ...                       ...  ...            ...       ...
4101615  12925  2022-09-01T00:19:05.510Z  ...             nc        nc
4101616  12926  2022-09-01T00:06:22.711Z  ...             ak        ak
4101617  12927  2022-09-01T00:02:18.320Z  ...             ci        ci
4101618  12928  2022-09-01T00:01:27.720Z  ...             nc        nc
4101619      0  1950-01-30T01:34:11.520Z  ...           ci.1      ci.2

[4101620 rows x 23 columns]

In [9]:
df.drop(['fuera'], axis = 1,inplace=True)

In [10]:
df.head()

                       time   latitude  ... locationSource magSource
0  1950-01-30T00:56:35.020Z    -53.472  ...         iscgem    iscgem
1  1950-01-29T05:21:16.030Z  34.000833  ...             ci        ci
2  1950-01-28T22:45:12.670Z  35.860333  ...             ci        ci
3  1950-01-28T22:36:21.460Z  35.836333  ...             ci        ci
4  1950-01-28T12:10:04.690Z       35.7  ...             ci        ci

[5 rows x 22 columns]

# Revisado de valores de las columnas

In [11]:
df['type'].unique()

array(['earthquake', 'quarry blast', 'nuclear explosion', 'mine collapse',
       'other event', 'explosion', 'sonic boom', 'chemical explosion',
       'rock burst', 'ice quake', 'rockslide', 'Rock Slide',
       'accidental explosion', 'landslide', 'mining explosion', 'quarry',
       'building collapse', 'acoustic noise', 'sonicboom', 'not reported',
       'experimental explosion', 'collapse', 'meteorite',
       'induced or triggered event', 'volcanic eruption', 'Ice Quake'],
      dtype=object)

In [12]:
df['status'].unique()

array(['reviewed', 'automatic', 'manual'], dtype=object)

In [13]:
df['locationSource'].unique()

array(['iscgem', 'ci', 'iscgemsup', 'ushis', 'pags', 'hv', 'official',
       'nc', 'uw', 'us', 'j', 's', 'm', 'b', 'a', 'r', 'p', 'e', 'nm',
       'c', 'h', 'w', 'v', 'l', 'ak', 'u', 'g', 't', 'se', 'gl', 'o',
       'ag', 'd', 'uu', 'brk', 'wes', 'pas', 'doe', 'ott', 'ren', 'slc',
       'bla', 'tul', 'pal', 'spe', 'tei', 'pgc', 'scp', 'co', 'slm',
       'ags', 'gcmt', 'but', 'ecx', 'bou', 'sea', 'hdc', 'hlw', 'snm',
       'exp', 'lak', 'mac', 'cle', 'aei', 'hoj', 'aeic', 'macr', 'spec',
       'teic', 'gen', 'guc', 'ldg', 'isk', 'mdd', 'upa', 'unm', 'mpr',
       'str', 'trn', 'rom', 'dja', 'fbb', 'zag', 'bgs', 'bse', 'usbr',
       'pdg', 'css', 'ath', 'gii', 'the', 'rsnc', 'fdf', 'aro', 'sko',
       'lju', 'tva', 'sjr', 'wel', 'tap', 'casc', 'mb', 'zur', 'pre',
       'nn', 'rspr', 'grf', 'obn', 'ryd', 'jsn', 'mel', 'ld', 'ppt',
       'nic', 'csc', 'buc', 'mrb', 'war', 'ogso', 'ssnc', 'car', 'aust',
       'dmn', 'indr', 'ber', 'nnc', 'lim', 'teh', 'snet', 'inmg', 'csem',
       'sja', 'alg', 'irsa', 'gfu', 'jma', 'thr', 'sof', 'bykl', 'upp',
       'gom', 'hel', 'nssp', 'bdf', 'dhmr', 'ceri', 'ndi', 'tri', 'tir',
       'beo', 'dbn', 'dda', 'zamg', 'ucr', 'qui', 'bhl', 'hvo', 'sdd',
       'ept', 'cnrm', 'bji', 'hon', 'pda', 'dnk', 'pr', 'oh', 'us_wel',
       'us_guc', 'us_unm', 'us_isk', 'us_ott', 'us_sja', 'us_aust',
       'us_teh', 'us_car', 'us_mdd', 'us_bgs', 'us_lim', 'us_rom',
       'us_trn', 'us_pgc', 'us_the', 'us_ath', 'us_qui', 'us_thr',
       'us_tul', 'us_buc', 'us_rsnc', 'us_snet', 'us_ecx', 'us_gcg',
       'us_ldg', 'us_inmg', 'ismp', 'rey', 'pivs', 'sors', 'bgrd',
       'ismpkansas', 'av', 'aacse', 'ok', 'tx', 'ew', 'at', 'pt', 'ci.1'],
      dtype=object)

In [14]:
df['magSource'].unique()

array(['iscgem', 'ci', 'iscgemsup', 'brk', 'pas', 'ushis', 'official',
       'mmt', 'sc', 'epb', 'ren', 'hvo', 'dg', 'slm', 'rot', 'upp', 'st',
       'mos', 'mat', 'hv', 'us', 'dor', 'yel', 'th', 'pal', 'gw', 'gol',
       'hrn', 'stt', 'dos', 'dw', 'isc', 'bak', 'bar', 'nc', 'her', 'uw',
       'jm', 'gb', 'som', 'hrm', 'erl', 'gs', 'pmr', 'tri', 'ath', 'bns',
       'ist', 'nm', 'csc', 'san', 'stu', 'tul', 'sea', 'bla', 'ak',
       'erda', 'slc', 'ott', 'zur', 'mso', '01020', 'rom', 'wes', 'lao',
       'aec', 'grc', 'sko', '01000', 'apt', 'hfs', 'isk', 'cll', 'ldg',
       'grf', 'prt', 'tir', 'gcmt', 'fir', 'se', 'can', 'aam', 'vie',
       'pru', 'ttg', 'lju', 'bly', 'tol', 'mhi', 'pgc', 'fur', 'war',
       'pro', '01009', '01023', 'uu', 'sal', 'rmp', 'mns', 'kra', 'oth',
       'cti', 'gib', 'vka', 'pre', 'kbn', 'bud', 'wel', 'gs$', 'kba',
       'nao', 'ibk', 'scp', 'ori', 'php', 'co', 'dle', 'dmu', 'bry',
       'dou', 'but', 'sda', 'aqu', 'bji', 'sfs', 'mox', 'vlo', 'hrv',
       'tei', 'esk', 'dkm', 'cvf', 'brt', 'dui', 'edu', 'alp', 'srn',
       'hcy', 'sro', 'ple', 'iva', 'nb2', 'ber', 'the', 'fdf', 'pag',
       'mgg', 'ulc', 'pvy', 'dg$', 'riv', 'koe', 'mlg', 'stk', 'elo',
       'voy', 'too', 'bfd', 'edi', 'css', 'rmq', 'klg', 'nau', 'knt',
       'cms', 'new', 'ifr', 'htl', 'mdd', 'kmi', 'ecp', 'bul', 'ucc',
       'cam', 'gcg', 'mth', 'bgs', 'crm', 'vay', 'aba', 'hdc', 'ecx',
       'wer', 'stb', 'prl', 'trn', 'asp', 'mof', 'aro', 'ned', 'lsz',
       'upa', 'zag', 'gzh', 'ave', 'bhl', 'jer', 'bmu', 'kuk', 'cnb',
       'pmg', 'mte', 'alg', 'frf', 'mm4', 'sjr', 'pto', 'uvc', 'gen',
       'qis', 'sso', 'hlw', 'str', 'jma', 'snm', 'sjs', 'beo', 'tio',
       'fel', 'vao', 'rba', 'sva', 'par', 'teh', 'ohr', 'jck', 'taf',
       'gsh', 'krw', 'bra', 'lic', 'pda', 'unm', 'lis', 'aei', 'gs/',
       'ndi', 'hoj', 'qui', 'gm$', 'lmm', 'buc', 'ryd', 'qlp', 'mpr',
       'eta', 'dda', 'gm/', 'rtc', 'bth', 'apy', 'car', 'sss', 'dbn',
       'dmn', 'aeic', 'duputel', 'ppt', 'teic', 'rusms', 'dja', 'fbb',
       'hyb', 'guc', 'gii', 'bse', 'pdg', 'usbr', 'ruvs', 'tva', 'rsnc',
       'tap', 'mb', 'casc', 'nn', 'rspr', 'brg', 'aust', 'jsn', 'mel',
       'ld', 'cig', 'csem', 'zamg', 'nic', 'ogso', 'ssnc', 'snet', 'indr',
       'thr', 'nied', 'nnc', 'sja', 'obn', 'irsa', 'gfu', 'niec', 'bhd',
       'meri', 'dhmr', 'sof', 'inmg', 'mrb', 'nssp', 'rey', 'lim', 'bdf',
       'igil', 'krsc', 'skhl', 'tif', 'ucr', 'exp', 'ceri', 'sbs', 'gfz',
       'cnrm', 'sdd', 'ept', 'azer', 'hel', 'pr', 'us_unm', 'us_isk',
       'us_sja', 'us_guc', 'us_ott', 'us_aust', 'us_gcmt', 'us_car',
       'us_rsnc', 'us_mdd', 'us_bgs', 'us_rom', 'us_pgc', 'us_the',
       'us_wel', 'us_tul', 'us_buc', 'us_ucr', 'us_zamg', 'us_teh',
       'us_ecx', 'us_lim', 'us_gcg', 'us_ldg', 'us_inmg', 'oh', 'ismp',
       'sors', 'bgrd', 'inet', 'ismpkansas', 'spec', 'av', 'aacse', 'ok',
       'tx', 'ew', 'at', 'pt', 'ci.2'], dtype=object)

In [15]:
df['magNst'].unique()

array([nan, 8.0, 4.0, 2.0, 6.0, 10.0, 11.0, 13.0, 5.0, 3.0, 12.0, 9.0,
       14.0, 7.0, 0.0, 1.0, 16.0, 15.0, 20.0, 17.0, 19.0, 18.0, 24.0,
       21.0, 23.0, 22.0, 26.0, 28.0, 25.0, 27.0, 29.0, 30.0, 35.0, 31.0,
       33.0, 34.0, 36.0, 56.0, 39.0, 40.0, 41.0, 45.0, 32.0, 95.0, 60.0,
       46.0, 37.0, 68.0, 82.0, 51.0, 53.0, 50.0, 49.0, 63.0, 38.0, 81.0,
       57.0, 55.0, 52.0, 67.0, 42.0, 47.0, 43.0, 69.0, 58.0, 62.0, 64.0,
       59.0, 70.0, 86.0, 76.0, 44.0, 54.0, 78.0, 71.0, 66.0, 72.0, 48.0,
       89.0, 65.0, 77.0, 79.0, 87.0, 73.0, 91.0, 93.0, 85.0, 61.0, 106.0,
       75.0, 96.0, 80.0, 74.0, 100.0, 102.0, 101.0, 99.0, 83.0, 90.0,
       84.0, 114.0, 94.0, 113.0, 97.0, 98.0, 104.0, 118.0, 88.0, 103.0,
       121.0, 107.0, 92.0, 110.0, 108.0, 136.0, 109.0, 111.0, 120.0,
       125.0, 135.0, 116.0, 112.0, 115.0, 105.0, 126.0, 124.0, 130.0,
       128.0, 131.0, 123.0, 127.0, 139.0, 161.0, 191.0, 134.0, 122.0,
       146.0, 156.0, 152.0, 144.0, 183.0, 153.0, 177.0, 141.0, 149.0,
       117.0, 154.0, 138.0, 137.0, 321.0, 151.0, 168.0, 132.0, 208.0,
       179.0, 231.0, 225.0, 304.0, 243.0, 328.0, 173.0, 170.0, 133.0,
       165.0, 163.0, 214.0, 280.0, 148.0, 129.0, 204.0, 215.0, 184.0,
       269.0, 142.0, 143.0, 119.0, 147.0, 150.0, 196.0, 140.0, 282.0,
       194.0, 182.0, 278.0, 187.0, 157.0, 230.0, 200.0, 360.0, 319.0,
       155.0, 160.0, 164.0, 145.0, 158.0, 171.0, 159.0, 167.0, 166.0,
       174.0, 198.0, 189.0, 162.0, 185.0, 175.0, 178.0, 188.0, 176.0,
       193.0, 195.0, 169.0, 224.0, 212.0, 181.0, 216.0, 201.0, 270.0,
       180.0, 334.0, 247.0, 190.0, 192.0, 245.0, 186.0, 238.0, 249.0,
       220.0, 233.0, 197.0, 172.0, 207.0, 206.0, 222.0, 203.0, 223.0,
       209.0, 217.0, 241.0, 210.0, 260.0, 199.0, 218.0, 229.0, 213.0,
       236.0, 219.0, 228.0, 258.0, 240.0, 211.0, 221.0, 205.0, 302.0,
       253.0, 226.0, 254.0, 248.0, 255.0, 246.0, 288.0, 286.0, 290.0,
       263.0, 289.0, 250.0, 261.0, 277.0, 264.0, 252.0, 364.0, 244.0,
       256.0, 274.0, 273.0, 279.0, 235.0, 267.0, 257.0, 242.0, 292.0,
       295.0, 268.0, 271.0, 276.0, 265.0, 284.0, 232.0, 251.0, 266.0,
       389.0, 374.0, 365.0, 361.0, 234.0, 367.0, 387.0, 386.0, 202.0,
       315.0, 303.0, 398.0, 385.0, 380.0, 407.0, 379.0, 383.0, 338.0,
       325.0, 310.0, 327.0, 372.0, 369.0, 331.0, 294.0, 275.0, 333.0,
       308.0, 299.0, 368.0, 353.0, 370.0, 345.0, 371.0, 285.0, 388.0,
       259.0, 378.0, 239.0, 350.0, 227.0, 335.0, 237.0, 390.0, 373.0,
       351.0, 382.0, 348.0, 393.0, 332.0, 343.0, 339.0, 366.0, 340.0,
       357.0, 392.0, 362.0, 323.0, 316.0, 283.0, 355.0, 320.0, 352.0,
       305.0, 272.0, 406.0, 306.0, 414.0, 287.0, 297.0, 401.0, 377.0,
       324.0, 291.0, 309.0, 358.0, 318.0, 381.0, 281.0, 341.0, 403.0,
       314.0, 337.0, 298.0, 408.0, 347.0, 329.0, 391.0, 396.0, 375.0,
       344.0, 330.0, 336.0, 354.0, 262.0, 301.0, 307.0, 376.0, 349.0,
       300.0, 342.0, 402.0, 346.0, 399.0, 311.0, 317.0, 359.0, 363.0,
       394.0, 293.0, 356.0, 313.0, 296.0, 322.0, 429.0, 438.0, 428.0,
       415.0, 418.0, 424.0, 413.0, 412.0, 430.0, 423.0, 419.0, 410.0,
       505.0, 538.0, 534.0, 516.0, 384.0, 461.0, 432.0, 435.0, 550.0,
       404.0, 586.0, 448.0, 312.0, 425.0, 512.0, 440.0, 563.0, 397.0,
       395.0, 411.0, 475.0, 485.0, 548.0, 486.0, 450.0, 444.0, 468.0,
       434.0, 447.0, 537.0, 501.0, 494.0, 581.0, 588.0, 556.0, 498.0,
       457.0, 506.0, 526.0, 484.0, 621.0, 417.0, 495.0, 439.0, 514.0,
       482.0, 644.0, 426.0, 409.0, 456.0, 540.0, 572.0, 463.0, 679.0,
       481.0, 531.0, 504.0, 458.0, 502.0, 650.0, 490.0, 431.0, 752.0,
       567.0, 462.0, 553.0, 459.0, 491.0, 591.0, 478.0, 549.0, 511.0,
       527.0, 532.0, 539.0, 533.0, 471.0, 483.0, 617.0, 613.0, 568.0,
       441.0, 454.0, 579.0, 623.0, 639.0, 326.0, 821.0, 518.0, 453.0,
       509.0, 657.0, 437.0, 422.0, 522.0, 497.0, 436.0, 405.0, 479.0,
       445.0, 400.0, 455.0, 562.0, 660.0, 528.0, 466.0, 460.0, 473.0,
       560.0, 636.0, 646.0, 684.0, 616.0, 558.0, 416.0, 535.0, 608.0,
       465.0, 525.0, 488.0, 582.0, 606.0, 421.0, 433.0, 469.0, 449.0,
       631.0, 565.0, 451.0, 493.0, 507.0, 521.0, 587.0, 496.0, 667.0,
       597.0, 529.0, 474.0, 600.0, 476.0, 503.0, 545.0, 603.0, 941.0,
       854.0, 489.0, 576.0, 541.0, 487.0, 519.0, 624.0, 573.0, 790.0,
       800.0, 774.0, 578.0, 427.0, 620.0, 577.0, 464.0, 477.0, 446.0,
       641.0, 452.0, 668.0, 663.0, 630.0, 604.0, 492.0, 605.0, 778.0,
       557.0, 618.0, 689.0, 508.0, 547.0, 655.0, 513.0, 742.0, 552.0,
       510.0, 592.0, 590.0, 610.0, 656.0, 515.0, 566.0, 651.0, 661.0,
       500.0, 420.0, 536.0, 672.0, 706.0, 640.0, 632.0, 443.0, 555.0,
       442.0, 559.0, 761.0, 627.0, 601.0, 499.0, 744.0, 554.0, 607.0,
       760.0, '6.0.1'], dtype=object)

In [16]:
df['net'].unique()

array(['iscgem', 'ci', 'iscgemsup', 'ushis', 'official', 'hv', 'nc', 'uw',
       'us', 'nm', 'ak', 'se', 'uu', 'gcmt', 'rusms', 'mb', 'nn', 'ld',
       'pr', 'ismpkansas', 'av', 'aacse', 'ok', 'tx', 'ew', 'at', 'pt'],
      dtype=object)

In [17]:
df['magType'].unique()

array(['mw', 'ml', 'mh', nan, 'uk', 'fa', 'ms', 'mb', 'md', 'lg', 'ma',
       'mlg', 'mun', 'mb_lg', 'mc', 'mwc', 'Unknown', 'mblg', 'm', 'mwb',
       'mww', 'mwr', 'Md', 'mdl', 'no', 'hn', 'Ml', 'Mb', 'me', 'ms_20',
       'mlr', 'mwp', 'mlv', 'Mi'], dtype=object)

In [18]:
df.head(2)

                       time   latitude  ... locationSource magSource
0  1950-01-30T00:56:35.020Z    -53.472  ...         iscgem    iscgem
1  1950-01-29T05:21:16.030Z  34.000833  ...             ci        ci

[2 rows x 22 columns]

# Creamos un nuevo dataframe con las columnas que vamos a utilizar

In [33]:
df_nuevo=df[['time','latitude','longitude','depth','mag','magType','nst','gap','dmin','rms','net','place','type']]

In [34]:
df_nuevo.head(2)

                       time  ...        type
0  1950-01-30T00:56:35.020Z  ...  earthquake
1  1950-01-29T05:21:16.030Z  ...  earthquake

[2 rows x 13 columns]

Analizamos bien la columna magType

In [35]:
df_nuevo['magType'].unique()

array(['mw', 'ml', 'mh', nan, 'uk', 'fa', 'ms', 'mb', 'md', 'lg', 'ma',
       'mlg', 'mun', 'mb_lg', 'mc', 'mwc', 'Unknown', 'mblg', 'm', 'mwb',
       'mww', 'mwr', 'Md', 'mdl', 'no', 'hn', 'Ml', 'Mb', 'me', 'ms_20',
       'mlr', 'mwp', 'mlv', 'Mi'], dtype=object)

# Cambiamos el tipo de dato a la columna mag

In [36]:
df_nuevo=df_nuevo.astype({'mag':'float32'})

# Utilizamos solo las magnitudes mayores a 1.5

In [37]:
mag_max_1=df_nuevo[df_nuevo['mag']>1.5]

Revisamos la diferencia de datos del dataset original al nuevo

In [38]:
#1.970.000 filas y 13 columnas
mag_max_1.shape

(1970471, 13)

In [39]:
#4 millones de filas y 22 columnas
df.shape

(4101620, 22)

# Filtramos solo los que sean earthquake

In [40]:
earthquake=mag_max_1[mag_max_1['type']=='earthquake']

In [41]:
# Consideramos que esto no considera una mejora significativa para nuestro modelo por lo que es mejor simplemente dejar esta columna y dejar los datos de esta
earthquake.shape

(1908310, 13)

# Borramos los nulos

In [42]:
mag_max_1.dropna(inplace=True)

C:\Users\juseb\AppData\Local\Temp\ipykernel_4372\105487757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mag_max_1.dropna(inplace=True)

In [43]:
mag_max_1.shape

(639152, 13)

# Guardamos el CSV

In [44]:
#original
df.to_csv('Salida2.csv')

In [45]:
mag_max_1.to_csv('Salida3.csv')

In [46]:
mag_max_1.head()

                       time  ...        type
1  1950-01-29T05:21:16.030Z  ...  earthquake
2  1950-01-28T22:45:12.670Z  ...  earthquake
3  1950-01-28T22:36:21.460Z  ...  earthquake
4  1950-01-28T12:10:04.690Z  ...  earthquake
5  1950-01-28T07:42:38.200Z  ...  earthquake

[5 rows x 13 columns]